=== Dajnowicz/XML/Definicja typu dokumentu - definicja elementów i atrybutów/zad6.dtd
<!ELEMENT zamowienie (adres, artykuly)>
<!ATTLIST zamowienie numer_zamowienia CDATA #REQUIRED>
<!ELEMENT adres (miejsce, ulica, kod_pocztowy)>
<!ELEMENT ulica (#PCDATA)>
<!ATTLIST adres termin_dostarczenia CDATA #IMPLIED>
<!ATTLIST adres kraj (Polska) #FIXED "Polska">
<!ELEMENT artykuly (artykul+)>
<!ELEMENT artykul (film|ksiazka|plyta)>
<!ATTLIST artykul id ID #REQUIRED>
<!ELEMENT film (tytul, autor, rok_wydania, czas_trwania)>
<!ELEMENT ksiazka (tytul, autor, rok_wydania, nr_wydania)>
<!ELEMENT plyta (tytul, wykonawca, wydawca, rok_wydania,czas_trwania)>
<!ELEMENT miejsce (#PCDATA)>
<!ELEMENT kod_pocztowy (#PCDATA)>
<!ELEMENT tytul (#PCDATA)>
<!ELEMENT rok_wydania (#PCDATA)>
<!ELEMENT czas_trwania (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT nr_wydania (#PCDATA)>
<!ELEMENT wykonawca (#PCDATA)>
<!ELEMENT wydawca (#PCDATA)>

=== Dajnowicz/XML/Definicja typu dokumentu - definicja elementów i atrybutów/zad6.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE zamowienie SYSTEM "zad6.dtd">
<zamowienie numer_zamowienia="Z13">
	<adres termin_dostarczenia='21-09-2019' kraj='Polska'>
		<miejsce>Dom na Gorze</miejsce>
		<ulica>Niebieska</ulica>
		<kod_pocztowy>23-312</kod_pocztowy>
	</adres>
	<artykuly>
		<artykul id='P23'>
			<film>
				<tytul>Telefon</tytul>
				<autor>Graham Test</autor>
				<rok_wydania>09-01-2017</rok_wydania>
				<czas_trwania>143 minuty</czas_trwania>
			</film>
		</artykul>
		<artykul id='P13'>
			<ksiazka>
				<tytul>U Informatyka</tytul>
				<autor>Iksemel Monitorowski</autor>
				<rok_wydania>01-03-2015</rok_wydania>
				<nr_wydania>A1-B13</nr_wydania>
			</ksiazka>
		</artykul>
		<artykul id='P1'>
			<plyta>
				<tytul>Za Hardwerem</tytul>
				<wykonawca>Klawisz</wykonawca>
				<wydawca>PC Sound</wydawca>
				<rok_wydania>12-04-2000</rok_wydania>
				<czas_trwania>90 minut</czas_trwania>
			</plyta>
		</artykul>
	</artykuly>
</zamowienie>
