=== Dajnowicz/XML/lab4/zad3.dtd
<!ENTITY % osoba "(dziecko*, student*, pracownik*)">
<!ELEMENT osoby (%osoba;)>


<!ENTITY % dane "(imie, nazwisko, data_urodzenia)">
<!ENTITY % pozycja "stanowisko">
<!ELEMENT dziecko %dane;>

<!ELEMENT student (%dane;) >
<!ELEMENT pracownik (%dane;, %pozycja;) >



<!ENTITY % r "#REQUIRED">
<!ENTITY % km "(k|m)">
<!ENTITY % cd "CDATA">

<!ATTLIST dziecko plec %km; %r;>
<!ATTLIST dziecko pesel %cd; %r;>
<!ATTLIST student plec %km; %r;>
<!ATTLIST student pesel %cd; %r;>
<!ATTLIST student nr_albumu %cd; %r;>
<!ATTLIST pracownik plec %km; %r;>
<!ATTLIST pracownik pesel %cd; %r;>


<!ENTITY % pc "#PCDATA">

<!ELEMENT imie (%pc;) >
<!ELEMENT nazwisko (%pc;) >
<!ELEMENT data_urodzenia (%pc;) >
<!ELEMENT nr_albumu (%pc;) >
<!ELEMENT stanowisko (%pc;) >

=== Dajnowicz/XML/Definicja typu dokumentu - definicja encji, sekcje warunkowe/zad3.xml
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE osoby SYSTEM "zad3.dtd">

<osoby>
    <dziecko plec="k" pesel="998924729824">
        <imie>Ada</imie>
        <nazwisko>Jakas</nazwisko>
        <data_urodzenia>23.02.2008</data_urodzenia>
    </dziecko>
    <student plec="k" pesel="998346729824" nr_albumu="255938">
        <imie>Karolina</imie>
        <nazwisko>Testowa</nazwisko>
        <data_urodzenia>12.04.1996</data_urodzenia>
    </student>
    <pracownik plec="m" pesel="998634729824">
        <imie>Tomasz</imie>
	<nazwisko>Nowy</nazwisko>
	<data_urodzenia>11.12.1990</data_urodzenia>
	<stanowisko>hejka</stanowisko>
    </pracownik>
</osoby>
