=== Dajnowicz/XML/lab4/zad7.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!ENTITY % NowaMatura "INCLUDE">
<!ENTITY % StaraMatura "IGNORE">
<!ENTITY % pcd "#PCDATA">

<!ELEMENT matura (egzamin*)>

<![%StaraMatura; [
<!ELEMENT egzamin (nazwa, ocena)>
<!ATTLIST egzamin rezultat (zaliczony|niezaliczony) #REQUIRED>
<!ELEMENT ocena (%pcd;)>
]]>

<![%NowaMatura; [
<!ELEMENT egzamin (nazwa, punkty)>
<!ELEMENT punkty (%pcd;)>
<!ATTLIST egzamin proc CDATA "0%">
<!ATTLIST egzamin lvl (pods|roz) "pods">

]]>

<!ELEMENT nazwa (%pcd;)>

=== Dajnowicz/XML/lab4/zad7.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE matura SYSTEM "zad7.dtd">

<matura>
	<egzamin lvl="pods" proc="23%">
		<nazwa>Jezyk Polski</nazwa>
		<punkty>20</punkty>
	</egzamin>
	<egzamin lvl ="roz" proc="30%">
		<nazwa>Matematyka</nazwa>
		<punkty>36</punkty>
	</egzamin>
	<egzamin lvl="pods" proc="70%">
		<nazwa>Angielski</nazwa>
		<punkty>3</punkty>
	</egzamin>
	<egzamin lvl="roz" proc="10%">
		<nazwa>Geografia</nazwa>
		<punkty>27</punkty>
	</egzamin>
</matura>
