=== Dajnowicz/XML/lab3/zad5.dtd
<!ELEMENT firma (nazwa?, dzial*)>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT dzial (pracownik+)>
<!ELEMENT pracownik (imie, nazwisko, data_ur)>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT data_ur (#PCDATA)>
<!ATTLIST pracownik plec (m|k|bd) "bd">
<!ATTLIST pracownik numer_pesel NMTOKEN #REQUIRED>
<!ATTLIST pracownik opis NMTOKENS #IMPLIED>

=== Dajnowicz/XML/lab3/zad5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE firma SYSTEM "zad5.dtd">
<firma>
	<nazwa>XmlCompany</nazwa>		
	<dzial> 
		<pracownik plec="m" numer_pesel="jednoslowo" opis="opcjonalne"> 
			<imie> Marcel</imie>
			<nazwisko>Dajnowicz</nazwisko>
			<data_ur>9 maj 1997</data_ur>
		</pracownik>
		<pracownik plec="k" numer_pesel="1212123" opis="jestem cool">
			<imie>Ja</imie>
			<nazwisko>Firana</nazwisko>
			<data_ur>10 czerwca 2000</data_ur>
		</pracownik>
	</dzial>
</firma>
