=== Dajnowicz/XML/lab3/zad6.dtd
<!ELEMENT korzen (wezel|lisc|galaz)>
<!ELEMENT wezel ((wezel,wezel) | (lisc,lisc) |(wezel, lisc)| (lisc,wezel))>
<!ELEMENT lisc (#PCDATA)>
<!ELEMENT galaz (#PCDATA)>
<!ATTLIST korzen kolor (czarny)  #FIXED "czarny">
<!ATTLIST wezel kolor (czerwony | czarny) #REQUIRED>
<!ATTLIST lisc kolor (czarny) #FIXED "czarny">

=== Dajnowicz/XML/lab3/zad6.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE korzen SYSTEM "zad6.dtd">
<korzen kolor="czarny">
	<wezel kolor="czerwony">
		<lisc kolor= "czarny"/>
		<lisc kolor= "czarny"/>
	</wezel>
	<wezel kolor="czarny">
		<wezel kolor="czerwony"> 
			<lisc kolor="czarny"/>
			<lisc kolor="czarny"/>
		</wezel>
		<lisc kolor="czarny"/>
	</wezel>
</korzen>
